node{
    try {
        def PROJECT = "itau-test"
        def REPO_GIT = "git@github.com:santos-edu/itau-test.git"
        def BRANCH_NAME = "main"

        message = "PIPELINE STARTED IN BRANCH $BRANCH_NAME - Build $BUILD_NUMBER"

        stage("cloning_$PROJECT") {
                checkout([$class: 'GitSCM',
                    userRemoteConfigs: [[url: "$REPO_GIT"]],
                    branches: [[name: "$BRANCH_NAME"]],
                    credentialsId: 'TxMVYzKaAYMhskKNiqav',
                    clean: false,
                    extensions: [[$class: 'SubmoduleOption',
                                    disableSubmodules: false,
                                    parentCredentials: false,
                                    recursiveSubmodules: true,
                                    reference: '',
                                    trackingSubmodules: false]],
                    doGenerateSubmoduleConfigurations: false,
                    submoduleCfg: []
                ])
        }

        stage('app_build') {
            dir(env.WORKSPACE) {
                sh """
                    echo app build
                """
            }
        }

        stage('unit_tests') {
            dir(env.WORKSPACE) {
                sh """
                    echo teste
                """
            }
        }

        stage('terraform_create_deploy') {
            dir(env.WORKSPACE) {
                sh """
                    cd terraform
                    #sed -i s/REPLICAS/2/ autoscalinggroup.tf
                    #sed -i s/REPLI_MAX/4/ autoscalinggroup.tf
                    terraform init
                    terraform apply -auto-approve
                    #sleep 1m
                    #sed -i s/2/1/ autoscalinggroup.tf
                    #sed -i s/4/2/ autoscalinggroup.tf
                    #terraform apply -auto-approve
                """
            }
        }

    } catch (error) {
        currentBuild.result = "FAILED"
        throw error
    } finally {
        currentBuild.result = "SUCCESS"
    }
}
